# Generated by Django 5.1 on 2024-11-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_sucursal', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Numerotelefono', models.CharField(max_length=50)),
                ('Correoelectronico', models.CharField(max_length=50)),
                ('Horario', models.CharField(max_length=10)),
                ('Paginaweb', models.CharField(max_length=10)),
            ],
        ),
    ]
