# Generated by Django 5.1.3 on 2024-11-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camiones',
            fields=[
                ('id_camion', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Matricula', models.CharField(max_length=50)),
                ('Modelo', models.CharField(max_length=50)),
                ('Marca', models.CharField(max_length=50)),
                ('Capacidadpasajeros', models.CharField(max_length=50)),
                ('Estadodelcamion', models.CharField(max_length=10)),
                ('Tipodemotor', models.CharField(max_length=10)),
            ],
        ),
    ]
